/**********************************************************************

	--- Qt Architect generated file ---

	File: QCheckout_MAINData.cpp
	Last generated: Tue Dec 1 18:01:59 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QCheckout_MAINData.h"

#define Inherited QWidget

#include <qbttngrp.h>

QCheckout_MAINData::QCheckout_MAINData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_2;
	qtarch_ButtonGroup_2 = new QButtonGroup( this, "ButtonGroup_2" );
	qtarch_ButtonGroup_2->setGeometry( 60, 60, 400, 195 );
	qtarch_ButtonGroup_2->setMinimumSize( 400, 195 );
	qtarch_ButtonGroup_2->setMaximumSize( 400, 195 );
	qtarch_ButtonGroup_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_2->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_2->setFrameStyle( 49 );
	qtarch_ButtonGroup_2->setTitle( "Misc. options :" );
	qtarch_ButtonGroup_2->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 5, 5, 510, 50 );
	qtarch_ButtonGroup_1->setMinimumSize( 10, 25 );
	qtarch_ButtonGroup_1->setMaximumSize( 32767, 55 );
	qtarch_ButtonGroup_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_1->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "Module name/path/alias to checkout from the server :" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	fNorecurs = new QCheckBox( qtarch_ButtonGroup_2, "CheckBox_1" );
	fNorecurs->setGeometry( 5, 20, 390, 30 );
	fNorecurs->setMinimumSize( 0, 0 );
	fNorecurs->setMaximumSize( 32767, 30 );
	fNorecurs->setFocusPolicy( QWidget::TabFocus );
	fNorecurs->setBackgroundMode( QWidget::PaletteBackground );
	fNorecurs->setFontPropagation( QWidget::NoChildren );
	fNorecurs->setPalettePropagation( QWidget::NoChildren );
	fNorecurs->setText( "Do not recurse into sub-folders" );
	fNorecurs->setAutoRepeat( FALSE );
	fNorecurs->setAutoResize( FALSE );

	fStdout = new QCheckBox( qtarch_ButtonGroup_2, "CheckBox_2" );
	fStdout->setGeometry( 5, 55, 390, 30 );
	fStdout->setMinimumSize( 0, 0 );
	fStdout->setMaximumSize( 32767, 30 );
	fStdout->setFocusPolicy( QWidget::TabFocus );
	fStdout->setBackgroundMode( QWidget::PaletteBackground );
	fStdout->setFontPropagation( QWidget::NoChildren );
	fStdout->setPalettePropagation( QWidget::NoChildren );
	fStdout->setText( "Checkout files to standard output (avoid stickiness)" );
	fStdout->setAutoRepeat( FALSE );
	fStdout->setAutoResize( FALSE );

	fModule = new QComboBox( TRUE, qtarch_ButtonGroup_1, "ComboBox_1" );
	fModule->setGeometry( 5, 20, 500, 25 );
	fModule->setMinimumSize( 0, 0 );
	fModule->setMaximumSize( 32767, 30 );
	fModule->setFocusPolicy( QWidget::StrongFocus );
	fModule->setBackgroundMode( QWidget::PaletteBackground );
	fModule->setFontPropagation( QWidget::NoChildren );
	fModule->setPalettePropagation( QWidget::NoChildren );
	fModule->setInsertionPolicy( QComboBox::AtBottom );
	fModule->setSizeLimit( 10 );
	fModule->setAutoResize( FALSE );

	qtarch_ButtonGroup_2->insert( fNorecurs );
	qtarch_ButtonGroup_2->insert( fStdout );


	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( qtarch_ButtonGroup_1, 1, 36 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( qtarch_ButtonGroup_1, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addSpacing( 15 );
	qtarch_layout_1_1->addWidget( fModule, 1, 36 );
	qtarch_layout_1->addWidget( qtarch_ButtonGroup_2, 1, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( qtarch_ButtonGroup_2, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addSpacing( 15 );
	qtarch_layout_1_2->addWidget( fNorecurs, 1, 36 );
	qtarch_layout_1_2->addWidget( fStdout, 1, 36 );
	resize( 520,260 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QCheckout_MAINData::~QCheckout_MAINData()
{
}
