/**********************************************************************

	--- Qt Architect generated file ---

	File: QCheckout_MAINData.h
	Last generated: Tue Dec 1 18:01:59 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QCheckout_MAINData_included
#define QCheckout_MAINData_included

#include <qwidget.h>
#include <qchkbox.h>
#include <qcombo.h>

class QCheckout_MAINData : public QWidget
{
    Q_OBJECT

public:

    QCheckout_MAINData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QCheckout_MAINData();

public slots:


protected slots:


protected:
    QCheckBox* fNorecurs;
    QCheckBox* fStdout;
    QComboBox* fModule;

};

#endif // QCheckout_MAINData_included
