/**********************************************************************

	--- Qt Architect generated file ---

	File: QCheckoutTabData.h
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QCheckoutTabData_included
#define QCheckoutTabData_included

#include <qtabdlg.h>

class QCheckoutTabData : public QTabDialog
{
    Q_OBJECT

public:

    QCheckoutTabData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QCheckoutTabData();

public slots:


protected slots:


protected:

};

#endif // QCheckoutTabData_included
