/**********************************************************************

	--- Qt Architect generated file ---

	File: QCommit_MAINData.cpp
	Last generated: Sat Nov 28 20:44:24 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QCommit_MAINData.h"

#define Inherited QWidget

#include <qlabel.h>
#include <qbttngrp.h>

QCommit_MAINData::QCommit_MAINData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 5, 5, 510, 168 );
	qtarch_ButtonGroup_1->setMinimumSize( 0, 0 );
	qtarch_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_1->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	fLog = new QMultiLineEdit( qtarch_ButtonGroup_1, "MultiLineEdit_1" );
	fLog->setGeometry( 5, 5, 500, 158 );
	fLog->setMinimumSize( 0, 0 );
	fLog->setMaximumSize( 32767, 32767 );
	fLog->setFocusPolicy( QWidget::StrongFocus );
	fLog->setBackgroundMode( QWidget::PaletteBase );
	fLog->setFontPropagation( QWidget::SameFont );
	fLog->setPalettePropagation( QWidget::SameFont );
	fLog->insertLine( "" );
	fLog->setReadOnly( FALSE );
	fLog->setOverwriteMode( FALSE );

	fCombo = new QComboBox( FALSE, this, "ComboBox_1" );
	fCombo->setGeometry( 5, 184, 253, 30 );
	fCombo->setMinimumSize( 0, 0 );
	fCombo->setMaximumSize( 32767, 30 );
	connect( fCombo, SIGNAL(activated(int)), SLOT(OnCombo(int)) );
	fCombo->setFocusPolicy( QWidget::StrongFocus );
	fCombo->setBackgroundMode( QWidget::PaletteBackground );
	fCombo->setFontPropagation( QWidget::NoChildren );
	fCombo->setPalettePropagation( QWidget::NoChildren );
	fCombo->setSizeLimit( 10 );
	fCombo->setAutoResize( FALSE );

	fNorecurs = new QCheckBox( this, "CheckBox_1" );
	fNorecurs->setGeometry( 5, 225, 510, 30 );
	fNorecurs->setMinimumSize( 0, 0 );
	fNorecurs->setMaximumSize( 32767, 30 );
	fNorecurs->setFocusPolicy( QWidget::TabFocus );
	fNorecurs->setBackgroundMode( QWidget::PaletteBackground );
	fNorecurs->setFontPropagation( QWidget::NoChildren );
	fNorecurs->setPalettePropagation( QWidget::NoChildren );
	fNorecurs->setText( "Do not recuse into sub-folders" );
	fNorecurs->setAutoRepeat( FALSE );
	fNorecurs->setAutoResize( FALSE );

	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 263, 184, 252, 30 );
	qtarch_Label_1->setMinimumSize( 0, 0 );
	qtarch_Label_1->setMaximumSize( 32767, 30 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( "<- Previous logs or CVS/Template" );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );


	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( qtarch_ButtonGroup_1, 4, 36 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( qtarch_ButtonGroup_1, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( fLog, 1, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( fCombo, 1, 36 );
	qtarch_layout_1_2->addWidget( qtarch_Label_1, 1, 36 );
	qtarch_layout_1->addWidget( fNorecurs, 1, 36 );
	resize( 520,260 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QCommit_MAINData::~QCommit_MAINData()
{
}
void QCommit_MAINData::OnCombo(int)
{
}
