/**********************************************************************

	--- Qt Architect generated file ---

	File: QCommitTabData.h
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QCommitTabData_included
#define QCommitTabData_included

#include <qtabdlg.h>

class QCommitTabData : public QTabDialog
{
    Q_OBJECT

public:

    QCommitTabData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QCommitTabData();

public slots:


protected slots:


protected:

};

#endif // QCommitTabData_included
