/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPrefsTabData.h
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QGetPrefsTabData_included
#define QGetPrefsTabData_included

#include <qtabdlg.h>

class QGetPrefsTabData : public QTabDialog
{
    Q_OBJECT

public:

    QGetPrefsTabData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QGetPrefsTabData();

public slots:


protected slots:


protected:

};

#endif // QGetPrefsTabData_included
