/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPrefs_CVSROOTData.h
	Last generated: Tue Nov 24 00:08:16 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QGetPrefs_CVSROOTData_included
#define QGetPrefs_CVSROOTData_included

#include <qwidget.h>
#include <qbttngrp.h>
#include <qradiobt.h>
#include <qcombo.h>

class QGetPrefs_CVSROOTData : public QWidget
{
    Q_OBJECT

public:

    QGetPrefs_CVSROOTData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QGetPrefs_CVSROOTData();

public slots:


protected slots:


protected:
    QComboBox* fCvsroot;
    QButtonGroup* fAuthen;
    QRadioButton* fLocal;
    QRadioButton* fRsh;
    QRadioButton* fPserver;
    QRadioButton* fKserver;
    QRadioButton* fSsh;
    QButtonGroup* fCvs;
    QRadioButton* fCvs110;

};

#endif // QGetPrefs_CVSROOTData_included
