/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPrefs_GLOBALSData.h
	Last generated: Mon Nov 23 22:23:01 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QGetPrefs_GLOBALSData_included
#define QGetPrefs_GLOBALSData_included

#include <qwidget.h>
#include <qchkbox.h>

class QGetPrefs_GLOBALSData : public QWidget
{
    Q_OBJECT

public:

    QGetPrefs_GLOBALSData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QGetPrefs_GLOBALSData();

public slots:


protected slots:


protected:
    QCheckBox* fReadonly;
    QCheckBox* fPrune;
    QCheckBox* fZ9;
    QCheckBox* fQuiet;
    QCheckBox* fAddcontrol;

};

#endif // QGetPrefs_GLOBALSData_included
