/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPasswordData.h
	Last generated: Tue Nov 24 16:06:59 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QGetPasswordData_included
#define QGetPasswordData_included

#include <qdialog.h>
#include <qlined.h>

class QGetPasswordData : public QDialog
{
    Q_OBJECT

public:

    QGetPasswordData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QGetPasswordData();

public slots:


protected slots:


protected:
    QLineEdit* fPassword;

};

#endif // QGetPasswordData_included
