/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPasswordData.cpp
	Last generated: Tue Nov 24 16:06:59 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QGetPasswordData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

QGetPasswordData::QGetPasswordData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 53248 )
{
	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 5, 5, 230, 37 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( "Enter your cvs password :" );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	fPassword = new QLineEdit( this, "LineEdit_1" );
	fPassword->setGeometry( 5, 47, 230, 36 );
	fPassword->setMinimumSize( 0, 0 );
	fPassword->setMaximumSize( 32767, 32767 );
	fPassword->setFocusPolicy( QWidget::StrongFocus );
	fPassword->setBackgroundMode( QWidget::PaletteBase );
	fPassword->setFontPropagation( QWidget::NoChildren );
	fPassword->setPalettePropagation( QWidget::NoChildren );
	fPassword->setText( "" );
	fPassword->setMaxLength( 32767 );
	fPassword->setEchoMode( QLineEdit::Password );
	fPassword->setFrame( TRUE );

	QPushButton* qtarch_PushButton_3;
	qtarch_PushButton_3 = new QPushButton( this, "PushButton_3" );
	qtarch_PushButton_3->setGeometry( 123, 88, 112, 37 );
	qtarch_PushButton_3->setMinimumSize( 0, 0 );
	qtarch_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_3, SIGNAL(clicked()), SLOT(accept()) );
	qtarch_PushButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setText( "OK" );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );
	qtarch_PushButton_3->setAutoDefault( TRUE );

	QPushButton* qtarch_PushButton_4;
	qtarch_PushButton_4 = new QPushButton( this, "PushButton_4" );
	qtarch_PushButton_4->setGeometry( 5, 88, 113, 37 );
	qtarch_PushButton_4->setMinimumSize( 0, 0 );
	qtarch_PushButton_4->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_4, SIGNAL(clicked()), SLOT(reject()) );
	qtarch_PushButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setText( "Cancel" );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( qtarch_Label_2, 1, 36 );
	qtarch_layout_1->addWidget( fPassword, 1, 36 );
	QBoxLayout* qtarch_layout_1_3 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_3, 1 );
	qtarch_layout_1_3->addStrut( 0 );
	qtarch_layout_1_3->addWidget( qtarch_PushButton_4, 1, 36 );
	qtarch_layout_1_3->addWidget( qtarch_PushButton_3, 1, 36 );
	resize( 240,130 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QGetPasswordData::~QGetPasswordData()
{
}
