/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPrefsTabData.cpp
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QGetPrefsTabData.h"

#define Inherited QTabDialog


QGetPrefsTabData::QGetPrefsTabData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	resize( 510,300 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QGetPrefsTabData::~QGetPrefsTabData()
{
}
