/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPrefs_CVSROOTData.cpp
	Last generated: Tue Nov 24 00:08:16 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QGetPrefs_CVSROOTData.h"

#define Inherited QWidget

#include <qlabel.h>

QGetPrefs_CVSROOTData::QGetPrefs_CVSROOTData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 12288 )
{
	fCvsroot = new QComboBox( TRUE, this, "ComboBox_2" );
	fCvsroot->setGeometry( 136, 20, 379, 30 );
	fCvsroot->setMinimumSize( 0, 30 );
	fCvsroot->setMaximumSize( 32767, 30 );
	fCvsroot->setFocusPolicy( QWidget::StrongFocus );
	fCvsroot->setBackgroundMode( QWidget::PaletteBackground );
	fCvsroot->setFontPropagation( QWidget::NoChildren );
	fCvsroot->setPalettePropagation( QWidget::NoChildren );
	fCvsroot->setInsertionPolicy( QComboBox::AtTop );
	fCvsroot->setSizeLimit( 32767 );
	fCvsroot->setAutoResize( FALSE );

	fAuthen = new QButtonGroup( this, "ButtonGroup_1" );
	fAuthen->setGeometry( 5, 70, 258, 185 );
	fAuthen->setMinimumSize( 10, 37 );
	fAuthen->setMaximumSize( 32767, 187 );
	fAuthen->setFocusPolicy( QWidget::NoFocus );
	fAuthen->setBackgroundMode( QWidget::PaletteBackground );
	fAuthen->setFontPropagation( QWidget::NoChildren );
	fAuthen->setPalettePropagation( QWidget::NoChildren );
	fAuthen->setFrameStyle( 49 );
	fAuthen->setTitle( "Authentication :" );
	fAuthen->setAlignment( 1 );

	fLocal = new QRadioButton( fAuthen, "RadioButton_6" );
	fLocal->setGeometry( 5, 12, 248, 30 );
	fLocal->setMinimumSize( 0, 0 );
	fLocal->setMaximumSize( 32767, 30 );
	fLocal->setFocusPolicy( QWidget::TabFocus );
	fLocal->setBackgroundMode( QWidget::PaletteBackground );
	fLocal->setFontPropagation( QWidget::NoChildren );
	fLocal->setPalettePropagation( QWidget::NoChildren );
	fLocal->setText( "Local mode" );
	fLocal->setAutoRepeat( FALSE );
	fLocal->setAutoResize( FALSE );

	fRsh = new QRadioButton( fAuthen, "RadioButton_1" );
	fRsh->setGeometry( 5, 47, 248, 29 );
	fRsh->setMinimumSize( 0, 0 );
	fRsh->setMaximumSize( 32767, 30 );
	fRsh->setFocusPolicy( QWidget::TabFocus );
	fRsh->setBackgroundMode( QWidget::PaletteBackground );
	fRsh->setFontPropagation( QWidget::NoChildren );
	fRsh->setPalettePropagation( QWidget::NoChildren );
	fRsh->setText( "Rsh ("".rhosts"" file)" );
	fRsh->setAutoRepeat( FALSE );
	fRsh->setAutoResize( FALSE );

	fPserver = new QRadioButton( fAuthen, "RadioButton_2" );
	fPserver->setGeometry( 5, 81, 248, 30 );
	fPserver->setMinimumSize( 0, 0 );
	fPserver->setMaximumSize( 32767, 30 );
	fPserver->setFocusPolicy( QWidget::TabFocus );
	fPserver->setBackgroundMode( QWidget::PaletteBackground );
	fPserver->setFontPropagation( QWidget::NoChildren );
	fPserver->setPalettePropagation( QWidget::NoChildren );
	fPserver->setText( "Password (""pserver"")" );
	fPserver->setAutoRepeat( FALSE );
	fPserver->setAutoResize( FALSE );

	fKserver = new QRadioButton( fAuthen, "RadioButton_3" );
	fKserver->setGeometry( 5, 116, 248, 29 );
	fKserver->setMinimumSize( 0, 0 );
	fKserver->setMaximumSize( 32767, 30 );
	fKserver->setFocusPolicy( QWidget::TabFocus );
	fKserver->setBackgroundMode( QWidget::PaletteBackground );
	fKserver->setFontPropagation( QWidget::NoChildren );
	fKserver->setPalettePropagation( QWidget::NoChildren );
	fKserver->setText( "Kerberos (""kserver"")" );
	fKserver->setAutoRepeat( FALSE );
	fKserver->setAutoResize( FALSE );

	fSsh = new QRadioButton( fAuthen, "RadioButton_4" );
	fSsh->setGeometry( 5, 150, 248, 30 );
	fSsh->setMinimumSize( 0, 0 );
	fSsh->setMaximumSize( 32767, 30 );
	fSsh->setFocusPolicy( QWidget::TabFocus );
	fSsh->setBackgroundMode( QWidget::PaletteBackground );
	fSsh->setFontPropagation( QWidget::NoChildren );
	fSsh->setPalettePropagation( QWidget::NoChildren );
	fSsh->setText( "Secure shell (""ssh"")" );
	fSsh->setAutoRepeat( FALSE );
	fSsh->setAutoResize( FALSE );

	fCvs = new QButtonGroup( this, "ButtonGroup_4" );
	fCvs->setGeometry( 268, 70, 247, 185 );
	fCvs->setMinimumSize( 0, 0 );
	fCvs->setMaximumSize( 32767, 32767 );
	fCvs->setFocusPolicy( QWidget::NoFocus );
	fCvs->setBackgroundMode( QWidget::PaletteBackground );
	fCvs->setFontPropagation( QWidget::NoChildren );
	fCvs->setPalettePropagation( QWidget::NoChildren );
	fCvs->setFrameStyle( 49 );
	fCvs->setTitle( "Cvs version :" );
	fCvs->setAlignment( 1 );

	fCvs110 = new QRadioButton( fCvs, "RadioButton_5" );
	fCvs110->setGeometry( 5, 12, 237, 30 );
	fCvs110->setMinimumSize( 0, 0 );
	fCvs110->setMaximumSize( 32767, 30 );
	fCvs110->setFocusPolicy( QWidget::TabFocus );
	fCvs110->setBackgroundMode( QWidget::PaletteBackground );
	fCvs110->setFontPropagation( QWidget::NoChildren );
	fCvs110->setPalettePropagation( QWidget::NoChildren );
	fCvs110->setText( "cvs-1.10" );
	fCvs110->setAutoRepeat( FALSE );
	fCvs110->setAutoResize( FALSE );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 5, 20, 126, 30 );
	qtarch_Label_2->setMinimumSize( 0, 30 );
	qtarch_Label_2->setMaximumSize( 32767, 30 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( "Enter the CVSROOT :" );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	fAuthen->insert( fLocal );
	fAuthen->insert( fRsh );
	fAuthen->insert( fPserver );
	fAuthen->insert( fKserver );
	fAuthen->insert( fSsh );

	fCvs->insert( fCvs110 );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 1 );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( qtarch_Label_2, 1, 36 );
	qtarch_layout_1_1->addWidget( fCvsroot, 3, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 5 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( fAuthen, 1, 36 );
	QBoxLayout* qtarch_layout_1_2_1 = new QBoxLayout( fAuthen, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_2_1->addStrut( 0 );
	qtarch_layout_1_2_1->addSpacing( 7 );
	qtarch_layout_1_2_1->addWidget( fLocal, 1, 36 );
	qtarch_layout_1_2_1->addWidget( fRsh, 1, 36 );
	qtarch_layout_1_2_1->addWidget( fPserver, 1, 36 );
	qtarch_layout_1_2_1->addWidget( fKserver, 1, 36 );
	qtarch_layout_1_2_1->addWidget( fSsh, 1, 36 );
	qtarch_layout_1_2->addWidget( fCvs, 1, 36 );
	QBoxLayout* qtarch_layout_1_2_2 = new QBoxLayout( fCvs, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_2_2->addStrut( 0 );
	qtarch_layout_1_2_2->addSpacing( 7 );
	qtarch_layout_1_2_2->addWidget( fCvs110, 1, 33 );
	resize( 520,260 );
	setMinimumSize( 520, 260 );
	setMaximumSize( 520, 260 );
}


QGetPrefs_CVSROOTData::~QGetPrefs_CVSROOTData()
{
}
