/**********************************************************************

	--- Qt Architect generated file ---

	File: QGetPrefs_GLOBALSData.cpp
	Last generated: Mon Nov 23 22:23:01 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QGetPrefs_GLOBALSData.h"

#define Inherited QWidget


QGetPrefs_GLOBALSData::QGetPrefs_GLOBALSData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	fReadonly = new QCheckBox( this, "CheckBox_1" );
	fReadonly->setGeometry( 5, 5, 510, 30 );
	fReadonly->setMinimumSize( 0, 30 );
	fReadonly->setMaximumSize( 32767, 30 );
	fReadonly->setFocusPolicy( QWidget::TabFocus );
	fReadonly->setBackgroundMode( QWidget::PaletteBackground );
	fReadonly->setFontPropagation( QWidget::NoChildren );
	fReadonly->setPalettePropagation( QWidget::NoChildren );
	fReadonly->setText( "Checkout read-only" );
	fReadonly->setAutoRepeat( FALSE );
	fReadonly->setAutoResize( FALSE );

	fPrune = new QCheckBox( this, "CheckBox_2" );
	fPrune->setGeometry( 5, 40, 510, 30 );
	fPrune->setMinimumSize( 0, 0 );
	fPrune->setMaximumSize( 32767, 30 );
	fPrune->setFocusPolicy( QWidget::TabFocus );
	fPrune->setBackgroundMode( QWidget::PaletteBackground );
	fPrune->setFontPropagation( QWidget::NoChildren );
	fPrune->setPalettePropagation( QWidget::NoChildren );
	fPrune->setText( "Prune (remove) empty directories" );
	fPrune->setAutoRepeat( FALSE );
	fPrune->setAutoResize( FALSE );

	fZ9 = new QCheckBox( this, "CheckBox_3" );
	fZ9->setGeometry( 5, 75, 510, 30 );
	fZ9->setMinimumSize( 0, 0 );
	fZ9->setMaximumSize( 32767, 30 );
	fZ9->setFocusPolicy( QWidget::TabFocus );
	fZ9->setBackgroundMode( QWidget::PaletteBackground );
	fZ9->setFontPropagation( QWidget::NoChildren );
	fZ9->setPalettePropagation( QWidget::NoChildren );
	fZ9->setText( "Enable TCP/IP compression" );
	fZ9->setAutoRepeat( FALSE );
	fZ9->setAutoResize( FALSE );

	fQuiet = new QCheckBox( this, "CheckBox_4" );
	fQuiet->setGeometry( 5, 110, 510, 30 );
	fQuiet->setMinimumSize( 0, 0 );
	fQuiet->setMaximumSize( 32767, 30 );
	fQuiet->setFocusPolicy( QWidget::TabFocus );
	fQuiet->setBackgroundMode( QWidget::PaletteBackground );
	fQuiet->setFontPropagation( QWidget::NoChildren );
	fQuiet->setPalettePropagation( QWidget::NoChildren );
	fQuiet->setText( "More quiet (less messages)" );
	fQuiet->setAutoRepeat( FALSE );
	fQuiet->setAutoResize( FALSE );

	fAddcontrol = new QCheckBox( this, "CheckBox_5" );
	fAddcontrol->setGeometry( 5, 145, 510, 30 );
	fAddcontrol->setMinimumSize( 0, 0 );
	fAddcontrol->setMaximumSize( 32767, 30 );
	fAddcontrol->setFocusPolicy( QWidget::TabFocus );
	fAddcontrol->setBackgroundMode( QWidget::PaletteBackground );
	fAddcontrol->setFontPropagation( QWidget::NoChildren );
	fAddcontrol->setPalettePropagation( QWidget::NoChildren );
	fAddcontrol->setText( "Add control when adding files" );
	fAddcontrol->setAutoRepeat( FALSE );
	fAddcontrol->setAutoResize( FALSE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( fReadonly, 1, 36 );
	qtarch_layout_1->addWidget( fPrune, 1, 36 );
	qtarch_layout_1->addWidget( fZ9, 1, 36 );
	qtarch_layout_1->addWidget( fQuiet, 1, 36 );
	qtarch_layout_1->addWidget( fAddcontrol, 1, 36 );
	resize( 520,260 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QGetPrefs_GLOBALSData::~QGetPrefs_GLOBALSData()
{
}
