/**********************************************************************

	--- Qt Architect generated file ---

	File: QImport_MAINData.h
	Last generated: Tue Dec 1 14:39:25 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QImport_MAINData_included
#define QImport_MAINData_included

#include <qwidget.h>
#include <qlined.h>
#include <qmlined.h>

class QImport_MAINData : public QWidget
{
    Q_OBJECT

public:

    QImport_MAINData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QImport_MAINData();

public slots:


protected slots:


protected:
    QLineEdit* fModule;
    QMultiLineEdit* fLog;
    QLineEdit* fVendor;
    QLineEdit* fRelease;

};

#endif // QImport_MAINData_included
