/**********************************************************************

	--- Qt Architect generated file ---

	File: QImportWarningData.cpp
	Last generated: Tue Dec 1 14:10:17 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QImportWarningData.h"

#define Inherited QDialog

#include <qpushbt.h>

QImportWarningData::QImportWarningData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	fText = new QMultiLineEdit( this, "MultiLineEdit_1" );
	fText->setGeometry( 5, 5, 360, 215 );
	fText->setMinimumSize( 0, 0 );
	fText->setMaximumSize( 32767, 32767 );
	fText->setFocusPolicy( QWidget::StrongFocus );
	fText->setBackgroundMode( QWidget::PaletteBase );
	fText->setFontPropagation( QWidget::SameFont );
	fText->setPalettePropagation( QWidget::SameFont );
	fText->insertLine( "" );
	fText->setReadOnly( TRUE );
	fText->setOverwriteMode( FALSE );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 135, 225, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(accept()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( "OK" );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );
	qtarch_PushButton_1->setAutoDefault( TRUE );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( fText, 6, 36 );
	qtarch_layout_1->addWidget( qtarch_PushButton_1, 1, 36 );
	resize( 370,260 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QImportWarningData::~QImportWarningData()
{
}
