/**********************************************************************

	--- Qt Architect generated file ---

	File: QImportReportData.h
	Last generated: Tue Dec 1 00:15:51 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QImportReportData_included
#define QImportReportData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qradiobt.h>
#include <qmlined.h>

class QImportReportData : public QDialog
{
    Q_OBJECT

public:

    QImportReportData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QImportReportData();

public slots:


protected slots:


protected:
    QButtonGroup* fGroup;
    QRadioButton* fbut0;
    QRadioButton* fbut1;
    QRadioButton* fbut2;
    QRadioButton* fbut3;
    QMultiLineEdit* fConflict;

};

#endif // QImportReportData_included
