/**********************************************************************

	--- Qt Architect generated file ---

	File: QImportTabData.h
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QImportTabData_included
#define QImportTabData_included

#include <qtabdlg.h>

class QImportTabData : public QTabDialog
{
    Q_OBJECT

public:

    QImportTabData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QImportTabData();

public slots:


protected slots:


protected:

};

#endif // QImportTabData_included
