/**********************************************************************

	--- Qt Architect generated file ---

	File: QImportWarningData.h
	Last generated: Tue Dec 1 14:10:17 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QImportWarningData_included
#define QImportWarningData_included

#include <qdialog.h>
#include <qmlined.h>

class QImportWarningData : public QDialog
{
    Q_OBJECT

public:

    QImportWarningData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QImportWarningData();

public slots:


protected slots:


protected:
    QMultiLineEdit* fText;

};

#endif // QImportWarningData_included
