/**********************************************************************

	--- Qt Architect generated file ---

	File: QLineCmdData.cpp
	Last generated: Fri Nov 27 00:06:14 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QLineCmdData.h"

#define Inherited QWidget

#include <qbttngrp.h>

QLineCmdData::QLineCmdData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 5, 5, 510, 196 );
	qtarch_ButtonGroup_1->setMinimumSize( 0, 0 );
	qtarch_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_1->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	fPath = new QLabel( this, "Label_1" );
	fPath->setGeometry( 177, 216, 338, 30 );
	fPath->setMinimumSize( 0, 0 );
	fPath->setMaximumSize( 32767, 30 );
	fPath->setFocusPolicy( QWidget::NoFocus );
	fPath->setBackgroundMode( QWidget::PaletteBackground );
	fPath->setFontPropagation( QWidget::NoChildren );
	fPath->setPalettePropagation( QWidget::NoChildren );
	fPath->setText( "" );
	fPath->setAlignment( 1313 );
	fPath->setMargin( -1 );

	fPathCheck = new QCheckBox( this, "CheckBox_3" );
	fPathCheck->setGeometry( 5, 206, 169, 30 );
	fPathCheck->setMinimumSize( 0, 0 );
	fPathCheck->setMaximumSize( 32767, 30 );
	connect( fPathCheck, SIGNAL(toggled(bool)), SLOT(OnCheckPath(bool)) );
	fPathCheck->setFocusPolicy( QWidget::TabFocus );
	fPathCheck->setBackgroundMode( QWidget::PaletteBackground );
	fPathCheck->setFontPropagation( QWidget::NoChildren );
	fPathCheck->setPalettePropagation( QWidget::NoChildren );
	fPathCheck->setText( "Execute from this path :" );
	fPathCheck->setAutoRepeat( FALSE );
	fPathCheck->setAutoResize( FALSE );

	fCmd = new QMultiLineEdit( qtarch_ButtonGroup_1, "MultiLineEdit_1" );
	fCmd->setGeometry( 5, 5, 500, 186 );
	fCmd->setMinimumSize( 0, 0 );
	fCmd->setMaximumSize( 32767, 32767 );
	fCmd->setFocusPolicy( QWidget::StrongFocus );
	fCmd->setBackgroundMode( QWidget::PaletteBase );
	fCmd->setFontPropagation( QWidget::SameFont );
	fCmd->setPalettePropagation( QWidget::SameFont );
	fCmd->insertLine( "" );
	fCmd->setReadOnly( FALSE );
	fCmd->setOverwriteMode( FALSE );


	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( qtarch_ButtonGroup_1, 4, 36 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( qtarch_ButtonGroup_1, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1_1->addStrut( 0 );
	qtarch_layout_1_1->addWidget( fCmd, 1, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 3, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 1 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( fPathCheck, 1, 9 );
	qtarch_layout_1_2->addWidget( fPath, 2, 36 );
	resize( 520,260 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QLineCmdData::~QLineCmdData()
{
}
void QLineCmdData::OnCheckPath(bool)
{
}
