/**********************************************************************

	--- Qt Architect generated file ---

	File: QLineCmdTabData.h
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QLineCmdTabData_included
#define QLineCmdTabData_included

#include <qtabdlg.h>

class QLineCmdTabData : public QTabDialog
{
    Q_OBJECT

public:

    QLineCmdTabData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QLineCmdTabData();

public slots:


protected slots:


protected:

};

#endif // QLineCmdTabData_included
