/**********************************************************************

	--- Qt Architect generated file ---

	File: QLineCmdData.h
	Last generated: Fri Nov 27 00:06:14 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QLineCmdData_included
#define QLineCmdData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qchkbox.h>
#include <qmlined.h>

class QLineCmdData : public QWidget
{
    Q_OBJECT

public:

    QLineCmdData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QLineCmdData();

public slots:


protected slots:

    virtual void OnCheckPath(bool);

protected:
    QLabel* fPath;
    QCheckBox* fPathCheck;
    QMultiLineEdit* fCmd;

};

#endif // QLineCmdData_included
