/**********************************************************************

	--- Qt Architect generated file ---

	File: QUpdate_MERGEData.h
	Last generated: Thu Nov 26 23:31:55 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QUpdate_MERGEData_included
#define QUpdate_MERGEData_included

#include <qwidget.h>
#include <qradiobt.h>
#include <qcombo.h>

class QUpdate_MERGEData : public QWidget
{
    Q_OBJECT

public:

    QUpdate_MERGEData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QUpdate_MERGEData();

public slots:


protected slots:

    virtual void OnTwo(bool);
    virtual void OnOne(bool);
    virtual void OnNone(bool);

protected:
    QRadioButton* fNoneRadio;
    QRadioButton* fOneRadio;
    QRadioButton* fTwoRadio;
    QComboBox* fRev1;
    QComboBox* fRev2;

};

#endif // QUpdate_MERGEData_included
