/**********************************************************************

	--- Qt Architect generated file ---

	File: QUpdate_MERGEData.cpp
	Last generated: Thu Nov 26 23:31:55 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QUpdate_MERGEData.h"

#define Inherited QWidget

#include <qbttngrp.h>

QUpdate_MERGEData::QUpdate_MERGEData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 5, 5, 510, 250 );
	qtarch_ButtonGroup_1->setMinimumSize( 0, 0 );
	qtarch_ButtonGroup_1->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_1->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "Merge options (locally merged) :" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	fNoneRadio = new QRadioButton( qtarch_ButtonGroup_1, "RadioButton_1" );
	fNoneRadio->setGeometry( 5, 59, 248, 30 );
	fNoneRadio->setMinimumSize( 0, 0 );
	fNoneRadio->setMaximumSize( 32767, 30 );
	connect( fNoneRadio, SIGNAL(toggled(bool)), SLOT(OnNone(bool)) );
	fNoneRadio->setFocusPolicy( QWidget::TabFocus );
	fNoneRadio->setBackgroundMode( QWidget::PaletteBackground );
	fNoneRadio->setFontPropagation( QWidget::NoChildren );
	fNoneRadio->setPalettePropagation( QWidget::NoChildren );
	fNoneRadio->setText( "None" );
	fNoneRadio->setAutoRepeat( FALSE );
	fNoneRadio->setAutoResize( FALSE );

	fOneRadio = new QRadioButton( qtarch_ButtonGroup_1, "RadioButton_2" );
	fOneRadio->setGeometry( 5, 129, 248, 30 );
	fOneRadio->setMinimumSize( 0, 0 );
	fOneRadio->setMaximumSize( 32767, 30 );
	connect( fOneRadio, SIGNAL(toggled(bool)), SLOT(OnOne(bool)) );
	fOneRadio->setFocusPolicy( QWidget::TabFocus );
	fOneRadio->setBackgroundMode( QWidget::PaletteBackground );
	fOneRadio->setFontPropagation( QWidget::NoChildren );
	fOneRadio->setPalettePropagation( QWidget::NoChildren );
	fOneRadio->setText( "Only with this rev./tag/branch :" );
	fOneRadio->setAutoRepeat( FALSE );
	fOneRadio->setAutoResize( FALSE );

	fTwoRadio = new QRadioButton( qtarch_ButtonGroup_1, "RadioButton_3" );
	fTwoRadio->setGeometry( 5, 198, 248, 30 );
	fTwoRadio->setMinimumSize( 0, 0 );
	fTwoRadio->setMaximumSize( 32767, 30 );
	connect( fTwoRadio, SIGNAL(toggled(bool)), SLOT(OnTwo(bool)) );
	fTwoRadio->setFocusPolicy( QWidget::TabFocus );
	fTwoRadio->setBackgroundMode( QWidget::PaletteBackground );
	fTwoRadio->setFontPropagation( QWidget::NoChildren );
	fTwoRadio->setPalettePropagation( QWidget::NoChildren );
	fTwoRadio->setText( "Plus with this rev/tag/branch :" );
	fTwoRadio->setAutoRepeat( FALSE );
	fTwoRadio->setAutoResize( FALSE );

	fRev1 = new QComboBox( TRUE, qtarch_ButtonGroup_1, "ComboBox_1" );
	fRev1->setGeometry( 258, 129, 247, 30 );
	fRev1->setMinimumSize( 0, 0 );
	fRev1->setMaximumSize( 32767, 30 );
	fRev1->setFocusPolicy( QWidget::StrongFocus );
	fRev1->setBackgroundMode( QWidget::PaletteBackground );
	fRev1->setFontPropagation( QWidget::NoChildren );
	fRev1->setPalettePropagation( QWidget::NoChildren );
	fRev1->setInsertionPolicy( QComboBox::AtBottom );
	fRev1->setSizeLimit( 10 );
	fRev1->setAutoResize( FALSE );

	fRev2 = new QComboBox( TRUE, qtarch_ButtonGroup_1, "ComboBox_2" );
	fRev2->setGeometry( 258, 198, 247, 30 );
	fRev2->setMinimumSize( 0, 0 );
	fRev2->setMaximumSize( 32767, 30 );
	fRev2->setFocusPolicy( QWidget::StrongFocus );
	fRev2->setBackgroundMode( QWidget::PaletteBackground );
	fRev2->setFontPropagation( QWidget::NoChildren );
	fRev2->setPalettePropagation( QWidget::NoChildren );
	fRev2->setInsertionPolicy( QComboBox::AtBottom );
	fRev2->setSizeLimit( 10 );
	fRev2->setAutoResize( FALSE );

	qtarch_ButtonGroup_1->insert( fNoneRadio );
	qtarch_ButtonGroup_1->insert( fOneRadio );
	qtarch_ButtonGroup_1->insert( fTwoRadio );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	qtarch_layout_1->addWidget( qtarch_ButtonGroup_1, 1, 36 );
	QGridLayout* qtarch_layout_1_1 = new QGridLayout( qtarch_ButtonGroup_1, 4, 2, 5, 5, NULL );
	qtarch_layout_1_1->addColSpacing( 0, 5 );
	qtarch_layout_1_1->setColStretch( 0, 1 );
	qtarch_layout_1_1->addColSpacing( 1, 5 );
	qtarch_layout_1_1->setColStretch( 1, 1 );
	qtarch_layout_1_1->addRowSpacing( 0, 0 );
	qtarch_layout_1_1->setRowStretch( 0, 1 );
	qtarch_layout_1_1->addRowSpacing( 1, 0 );
	qtarch_layout_1_1->setRowStretch( 1, 2 );
	qtarch_layout_1_1->addWidget( fNoneRadio, 1, 0, 36 );
	qtarch_layout_1_1->addRowSpacing( 2, 0 );
	qtarch_layout_1_1->setRowStretch( 2, 2 );
	qtarch_layout_1_1->addWidget( fOneRadio, 2, 0, 36 );
	qtarch_layout_1_1->addWidget( fRev1, 2, 1, 36 );
	qtarch_layout_1_1->addRowSpacing( 3, 0 );
	qtarch_layout_1_1->setRowStretch( 3, 2 );
	qtarch_layout_1_1->addWidget( fTwoRadio, 3, 0, 36 );
	qtarch_layout_1_1->addWidget( fRev2, 3, 1, 36 );
	resize( 520,260 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QUpdate_MERGEData::~QUpdate_MERGEData()
{
}
void QUpdate_MERGEData::OnNone(bool)
{
}
void QUpdate_MERGEData::OnOne(bool)
{
}
void QUpdate_MERGEData::OnTwo(bool)
{
}
