/**********************************************************************

	--- Qt Architect generated file ---

	File: QUpdateTabData.h
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef QUpdateTabData_included
#define QUpdateTabData_included

#include <qtabdlg.h>

class QUpdateTabData : public QTabDialog
{
    Q_OBJECT

public:

    QUpdateTabData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~QUpdateTabData();

public slots:


protected slots:


protected:

};

#endif // QUpdateTabData_included
