/**********************************************************************

	--- Qt Architect generated file ---

	File: QUpdateTabData.cpp
	Last generated: Mon Nov 23 23:04:20 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "QUpdateTabData.h"

#define Inherited QTabDialog


QUpdateTabData::QUpdateTabData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	resize( 510,300 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


QUpdateTabData::~QUpdateTabData()
{
}
