//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wincvs.rc
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDB_LIGHTBULB                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_TIP                         105
#define CG_IDS_TIPOFTHEDAY              106
#define CG_IDS_TIPOFTHEDAYMENU          107
#define CG_IDS_DIDYOUKNOW               108
#define CG_IDS_FILE_ABSENT              109
#define CG_IDP_FILE_CORRUPT             110
#define CG_IDS_TIPOFTHEDAYHELP          111
#define IDB_SPLASH                      112
#define IDC_OPTIONCHECK_BUTTON          113
#define IDR_MAINFRAME                   128
#define IDR_WINCVSTYPE                  129
#define IDS_DEFFONT                     129
#define IDR_BROWSER                     129
#define IDD_PASSWRD                     132
#define IDD_ALERT                       134
#define IDD_PREFS_GLOBALS               136
#define IDD_CHECKOUT_MAIN               137
#define IDD_COMMIT_MAIN                 138
#define IDD_IMPORT_MAIN                 139
#define IDD_IMPORT_OPTIONS              140
#define IDD_CMDLINE_MAIN                142
#define IDD_IMPORTFILTER                143
#define IDD_WARNINGDESC                 145
#define IDD_ENTRYDESC                   146
#define IDD_UPDATE_MAIN                 147
#define IDD_UPDATE_MERGE                149
#define IDD_LOG_MAIN                    150
#define IDD_LOG_FILTERS                 152
#define IDB_SMALLICONS                  152
#define IDD_DIFF_OPTIONS                153
#define IDD_DIFF_MAIN                   154
#define IDD_UPDATE_OPTIONS              155
#define IDD_PREFS_WINCVS                156
#define IDR_FILELIST                    157
#define IDR_MULTIUSER                   158
#define IDR_GRAPH                       161
#define IDR_STATEICONS                  164
#define IDR_TAGS                        165
#define IDD_INIT_MAIN                   165
#define IDR_WORKSPACE                   173
#define IDB_LOCATE                      176
#define IDD_PROGRESS                    177
#define IDB_ABOUT                       180
#define IDD_CUSTOMIZE                   181
#define IDR_CUSTMENUS                   182
#define IDB_PYTHON                      183
#define IDD_SAVESETTINGS                184
#define IDB_IDLE                        185
#define IDR_FILTER                      186
#define IDD_COMMIT_OPTIONS              186
#define IDB_HISTLOC                     187
#define IDD_PREFS_CVSCMD_DIALOGS        191
#define IDD_ANNOTATE_MAIN               192
#define IDD_GRAPH_OPTIONS               193
#define IDD_EDITMESSAGE                 195
#define IDD_ADMINOPTION                 196
#define IDD_EDITORMON                   197
#define IDD_NOPYTHON                    198
#define IDD_TAG_MAIN                    199
#define IDD_RTAG_MAIN                   200
#define IDD_RTAG_OPTIONS                201
#define IDD_STATUS_MAIN                 203
#define IDD_ITEM_LIST                   205
#define IDD_LOGIN_MAIN                  206
#define IDR_ITEMLIST                    207
#define IDD_PREFS_CVS                   207
#define IDB_MODULES                     208
#define IDD_RELEASE_MAIN                208
#define IDB_IMPORT                      209
#define IDD_SELECTION_DETAILS           209
#define IDD_FILTERBAR_OPTIONS           212
#define IDD_FILTER_SELECTION            213
#define IDD_MULTILINE_ENTRY             214
#define IDD_CVSTEMPLATE                 218
#define IDD_OPEN_MAIN                   219
#define IDI_MB_STOP                     220
#define IDI_MB_INFORMATION              221
#define IDI_MB_QUESTION                 222
#define IDI_MB_EXCLAMATION              223
#define IDD_CVSROOT                     224
#define IDD_EDITKEYWORD                 226
#define IDD_CVSROOT_ENTRY               227
#define IDD_SUBSTMODE_ENTRY             228
#define IDD_PREFS_GENERAL_DUMMY         229
#define IDD_REMOVE_MAIN                 230
#define IDR_SUBSTMODE                   232
#define IDB_BUTTON_POPUP                234
#define IDC_CVSROOT                     1000
#define IDC_BULB                        1001
#define IDC_STARTUP                     1003
#define IDC_HAS_COMPRESSION             1004
#define IDC_NEXTTIP                     1005
#define IDC_PRUNE_EMPTY_DIR             1006
#define IDC_TIPSTRING                   1007
#define IDC_ENCRYPTION                  1008
#define IDC_UNIX_LF                     1009
#define IDC_NO_SPLASH_SCREEN            1011
#define IDC_CONTROL_ADDED_FILES         1013
#define IDC_FILEPATH                    1014
#define IDC_PASSWORD                    1015
#define IDC_AUTO_LOGOUT                 1016
#define IDC_SPIN_AUTO_LOGOUT_TIME       1017
#define IDC_REFRESH_INACTIVE            1018
#define IDC_REFRESH_INACTIVE_TIME       1019
#define IDC_SPIN_REFRESH_INACTIVE_TIME  1020
#define IDC_MATCH_ENTRIES_CASE          1021
#define IDC_SMART_SORTING               1022
#define IDC_BROWSE_CVSROOT              1024
#define IDC_MULTILINE_ENTRY             1025
#define IDC_STDOUT                      1027
#define IDC_MODNAME                     1028
#define IDC_BROWSE_PATH                 1029
#define IDC_TAGNAME                     1030
#define IDC_NORECURS                    1031
#define IDC_PATH                        1032
#define IDC_FORCE_HEAD_REV              1033
#define IDC_COPY_PATH                   1034
#define IDC_OVERWRITE                   1035
#define IDC_HAS_REV                     1036
#define IDC_MULTILINE_ENTRY_WRAP        1037
#define IDC_RESET_STICKY                1038
#define IDC_CREATE_MISSING_DIR          1039
#define IDC_GET_CLEAN_COPY              1040
#define IDC_ENTRIES_LIST                1048
#define IDC_CONFLICT_DESC               1049
#define IDC_ENTRY_EDIT                  1050
#define IDC_WARNING_DESC                1051
#define IDC_ENTRYSTATE_NO_CHANGE        1052
#define IDC_HAS_DATE                    1053
#define IDC_ENTRYSTATE_FORCE_TEXT       1054
#define IDC_ENTRYSTATE_IGNORE           1055
#define IDC_REV_TAG                     1056
#define IDC_ENTRYSTATE_NO_EXPANSION     1057
#define IDC_DATE1                       1059
#define IDC_STATES                      1061
#define IDC_DATE2                       1062
#define IDC_REV_TAG2                    1063
#define IDC_HAS_USERS                   1065
#define IDC_NOTAGS                      1066
#define IDC_HEADERS                     1068
#define IDC_SUPRESS_HEADER              1069
#define IDC_HAS_PATH                    1070
#define IDC_HEADERS_DESC                1071
#define IDC_CVSRCSOUTPUT                1072
#define IDC_ADD_SELECTION               1073
#define IDC_HOME                        1074
#define IDC_ADD_DEFAULT                 1075
#define IDC_ENTRYSTATE_FORCE_BINARY     1076
#define IDC_DATE                        1077
#define IDC_ENTRYSTATE_FORCE_UNICODE    1078
#define IDC_USERS                       1081
#define IDC_DEFAULT_BRANCH              1082
#define IDC_COLOR_STATE                 1083
#define IDC_RCS_FILENAMES_ONLY          1084
#define IDC_ISDATE1                     1085
#define IDC_ISDATE2                     1086
#define IDC_REV_TAG1                    1087
#define IDC_RELEASE_TAG                 1089
#define IDC_BAR_TREE                    1091
#define IDC_USE_EXTERNAL_DIFF           1092
#define IDC_BULK_UPDATE                 1093
#define IDC_ATTIC                       1094
#define IDC_CHECK_UNMODIFIED            1098
#define IDC_MULTILINE_POSITION          1099
#define IDC_HAS_ALTERNATE_CVS           1100
#define IDC_ALTERNATE_CVS               1102
#define IDC_MULTILINE_PREV_ENTRY        1104
#define IDC_BROWSE_FILENAME             1105
#define IDC_WINCVSVER                   1107
#define IDC_AUTO_LOGOUT_TIME            1110
#define IDC_FORCE_CVSROOT               1114
#define IDC_HELP_INIT                   1116
#define IDC_PROGRESS                    1118
#define IDC_COMPRESSION                 1119
#define IDC_SPIN_COMPRESSION            1120
#define IDC_WINCVSURL                   1121
#define IDC_ALLCMDS                     1122
#define IDC_CVSGUISFURL                 1123
#define IDC_ADD                         1125
#define IDC_REMOVE                      1126
#define IDC_UP                          1127
#define IDC_DELETE_ALL_FILES            1128
#define IDC_DOWN                        1129
#define IDC_DELETE_CVS_INFO             1130
#define IDC_MENULIST                    1131
#define IDC_MULTILINE_WORDWRAP          1133
#define IDC_IGNOREWHITESPACE            1135
#define IDC_IGNORECASE                  1136
#define IDC_UNIFIEDDIFF                 1138
#define IDC_CHECKOUT_DIR                1139
#define IDC_OVERRIDE_CHECKOUT_DIR       1140
#define IDC_DEFAULT_CVSIGNORE           1141
#define IDC_FORCE_COMMIT                1142
#define IDC_SERVER_CVSWRAPPERS          1143
#define IDC_FILES_MODIFICATION_TIME     1144
#define IDC_FORCE_RECURSE               1145
#define IDC_CREATE_SANDBOX              1146
#define IDC_FORCE_REVISION              1147
#define IDC_NO_MODULE_PROGRAM           1148
#define IDC_VENDOR_TAG                  1149
#define IDC_CHECK_VALID_EDITS           1150
#define IDC_REPOSITORY_PATH             1153
#define IDC_COLOR_SELECTION             1159
#define IDC_FORCE_KEY_SHIFT             1160
#define IDC_FORCE_KEY_CTRL              1161
#define IDC_CONSOLE                     1162
#define IDC_ISDATE                      1164
#define IDC_REV_TAG_DATE                1165
#define IDC_DIFF                        1166
#define IDC_FILETODIFF                  1168
#define IDC_COLOR_MERGE                 1169
#define IDC_RESET_COLORS                1170
#define IDC_COLOR_HEADER                1171
#define IDC_COLOR_TAG                   1172
#define IDC_RGB_HEADER                  1173
#define IDC_RGB_TAG                     1174
#define IDC_RGB_BRANCH                  1175
#define IDC_RGB_NODE                    1176
#define IDC_RGB_DEAD                    1177
#define IDC_RGB_STATE                   1178
#define IDC_COLOR_BRANCH                1179
#define IDC_COLOR_NODE                  1180
#define IDC_SELECTION                   1181
#define IDC_COLOR_SHADOW                1182
#define IDC_COLOR_DEAD                  1183
#define IDC_RGB_SELECTION               1184
#define IDC_RGB_SHADOW                  1185
#define IDC_RGB_MERGE                   1186
#define IDC_TEMPFILE                    1187
#define IDC_REMIND                      1188
#define IDC_PYTHON_URL                  1189
#define IDC_PREVIEWINFO                 1190
#define IDC_HAS_DATE1                   1192
#define IDC_HAS_DATE2                   1193
#define IDC_GRPBOX_TEXT                 1194
#define IDC_TAGDESC_TEXT                1195
#define IDC_MODULEDESC_TEXT             1196
#define IDC_OUTPUT_QUICK                1197
#define IDC_OUTPUT_VERBOSE              1198
#define IDC_BROWSE_TAG                  1199
#define IDC_OUTPUT_STANDARD             1200
#define IDC_BROWSE_READ_FROM            1201
#define IDC_BROWSE_TAG1                 1202
#define IDC_BROWSE_TAG2                 1203
#define IDC_BROWSE_MODNAME              1205
#define IDC_ITEM_LIST                   1206
#define IDC_REFRESH_ITEMS               1207
#define IDC_READ_FROM                   1209
#define IDC_ITEM                        1210
#define IDC_ITEM_LABEL                  1211
#define IDC_ITEM_LIST_OPTION            1212
#define IDC_GROUP_OPTIONS               1215
#define IDC_HELPLOGIN                   1216
#define IDC_COMPARE_TYPE                1217
#define IDC_KEYWORD_OPT                 1218
#define IDC_KEYWORD_DESC                1219
#define IDC_DIFFOPTIONS                 1220
#define IDC_BROWSE_DIFFOPTIONS          1221
#define IDC_BROWSE_SELECTION            1223
#define IDC_DELETE_DIRECTORY            1224
#define IDC_PROGRESS_TEXT               1225
#define IDC_SELECTION_LIST              1226
#define IDC_FILENAME                    1227
#define IDC_REVISION_SPIN               1228
#define IDC_REVISION                    1229
#define IDC_AUTO_REFRESH                1230
#define IDC_HAS_BRANCHID                1231
#define IDC_BRANCHID                    1232
#define IDC_BROWSE_BRANCHID             1233
#define IDC_MOVDEL_BRANCH               1234
#define IDC_DONT_SHORTEN_PATHS          1235
#define IDC_REACTION_SPEED              1236
#define IDC_REACTION_SPEED_SPIN         1237
#define IDC_FILTER_CONTENTS             1238
#define IDC_FILTER                      1239
#define IDC_REACTION_SPEED_SECONDS      1240
#define IDC_CTRL_PRESSED_ON_OK          1241
#define IDC_MULTILINE_TYPE              1242
#define IDC_NO_VENDOR_RELEASE_TAGS      1243
#define IDC_MULTILINE_ENTRY_STATIC      1244
#define IDC_MULTILINE_GO_ACTION         1245
#define IDC_OTHER_BUTTON                1246
#define IDC_MULTILINE_ACTION            1247
#define IDC_TEMPLATE_LIST               1248
#define IDC_TEMPLATE_PREVIEW            1249
#define IDC_ICON_STATIC                 1250
#define IDC_MESSAGE_DETAILS             1251
#define IDC_ALERT_MESSAGE               1252
#define IDC_SHOW_CVS_METHOD             1253
#define IDC_ACTION                      1254
#define IDC_ACTION_DESC                 1255
#define IDC_SAME_ACTION_NEXT_TIME       1256
#define IDC_PROTOCOL_DESC               1257
#define IDC_PROTOCOL                    1258
#define IDC_KEYWORDLIST                 1259
#define IDC_CLEAR_KEYWORD               1260
#define IDC_KEYWORDLIST_DESC            1261
#define IDC_EDIT_KEYWORD                1262
#define IDC_PROTOCOL_KEYWORD            1263
#define IDC_KEYWORD_DESCRIPTION         1264
#define IDC_KEYWORD_VALUE               1265
#define IDC_OVERWRITE_RELEASE_TAGS      1266
#define IDC_IMPORT_FILTER               1267
#define IDC_CURRENT_DIFF_OPTIONS        1268
#define IDC_DIFF_OPTION_LIST            1269
#define IDC_DIFF_OPTION_DESCRIPTION     1270
#define IDC_STATICGROUP_SELECTOPTIONS   1271
#define IDC_STATIC_CURRENTOPTIONS       1272
#define IDC_STATIC_OPTDESC              1273
#define IDC_APPLY                       1274
#define IDC_SETTINGS_NAME               1275
#define IDC_COPY_SETTINGS               1276
#define IDC_COPY_SETTINGS_NAME          1277
#define IDC_PREVIEW_CVSROOT             1278
#define IDC_RANGE_REV_TAG               1279
#define IDC_RANGE_DATE                  1280
#define IDC_HAS_STATES                  1281
#define IDC_LAST_CHECKIN_TIME           1282
#define IDC_CASE_SENSITIVE_NAMES        1283
#define IDC_THREE_WAY_CONFLICTS         1284
#define IDC_BRANCHPOINT_MERGE           1285
#define IDC_MERGE_TYPE                  1286
#define IDC_CVSROOT_ENTRY_STATIC        1287
#define IDC_SUBSTMODE_ENTRY_STATIC      1288
#define IDC_CMDLINE_LIMIT               1289
#define IDC_ENABLE_CMDLINE_LIMIT        1290
#define IDC_BROWSE_KEYWORD              1291
#define IDC_CVSROOT_MIGRATION_URL       1294
#define IDC_CHECKOUTATTRIBUTE           1295
#define IDC_CVSMESSAGES                 1296
#define IDC_SKIP_DIALOGS                1297
#define IDC_PROMPT                      1298
#define IDC_WINCVS_SETTINGS_LIST        1299
#define IDC_BROWSE_WINCVS_SETTINGS      1300
#define IDC_CLEAR_WINCVS_SETTINGS       1301
#define IDC_WINCVS_SETTINGS_TYPE        1302
#define IDC_BULK_ANNOTATE               1303
#define IDC_FILES_REMOVAL_TYPE          1304
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_APP_PREFERENCES              32775
#define ID_APP_CMDLINE                  32776
#define ID_APP_LOGIN                    32779
#define ID_STOPCVS                      32795
#define ID_BROWSER_OPEN                 32797
#define ID_VIEW_BROWSER_BAR             32798
#define ID_UPDATEBF                     32799
#define ID_COMMITBF                     32800
#define ID_ADDBF                        32801
#define ID_VIEW_SMALLICONS              32802
#define ID_VIEW_FULLLIST                32803
#define ID_VIEW_ROWDETAILS              32804
#define ID_VIEW_FILES_BAR               32805
#define ID_VIEW_UPDATE                  32806
#define ID_VIEW_COMMIT                  32807
#define ID_VIEW_ADD                     32808
#define ID_VIEW_WORKSPACE               32809
#define ID_MENUBAR                      32810
#define ID_VIEW_ADDB                    32811
#define ID_VIEW_RMV                     32812
#define IDS_COMBOBROWSER                32813
#define ID_VIEW_RELOAD                  32814
#define ID_VIEW_NEXTWINDOW              32815
#define ID_VIEW_PREVWINDOW              32816
#define ID_VIEW_UPONE                   32826
#define ID_VIEW_TRASH                   32830
#define ID_VIEW_DIFF                    32833
#define ID_VIEW_LOG                     32834
#define ID_VIEW_STATUS                  32835
#define ID_VIEW_LOCKF                   32836
#define ID_VIEW_UNLOCKF                 32837
#define ID_VIEW_MULTI_BAR               32838
#define ID_MENUITEM32840                32840
#define ID_VIEW_WATCHON                 32843
#define ID_VIEW_WATCHOFF                32844
#define ID_VIEW_EDIT                    32845
#define ID_VIEW_UNEDIT                  32846
#define ID_VIEW_RELEASE                 32847
#define ID_VIEW_WATCHERS                32857
#define ID_VIEW_EDITORS                 32858
#define ID_CUST_FILES_MENU              32859
#define ID_CUST_FOLDER_MENU             32860
#define ID_APP_CREDITS                  32872
#define ID_APP_COPYRIGHTS               32873
#define ID_GRAPH_CLOSE                  32874
#define ID_VIEW_GRAPH                   32875
#define ID_APP_RTAGCREATE               32881
#define ID_APP_RTAGDELETE               32882
#define ID_APP_RTAGBRANCH               32883
#define ID_VIEW_TAG                     32884
#define ID_VIEW_TAGNEW                  32886
#define ID_VIEW_TAGDELETE               32887
#define ID_VIEW_TAGBRANCH               32888
#define ID_VIEW_TAGS_BAR                32889
#define ID_VIEW_CONSOLE_BAR             32898
#define ID_VIEW_EXPLORE                 32899
#define ID_HISTORYBROWSE                32900
#define ID_VIEW_QUERYUPDATE             32901
#define ID_VIEW_IGNORE                  32902
#define ID_APP_LOGOUT                   32906
#define ID_VIEW_EDITSEL                 32908
#define ID_VIEW_EDITSELDEF              32909
#define ID_ACCEL32911                   32911
#define ID_VIEWW_INIT                   32912
#define ID_VIEW_IMPORT                  32913
#define ID_VIEW_INIT                    32914
#define ID_VIEW_CHECKOUT                32915
#define ID_VIEW_DELREV                  32916
#define ID_VIEW_SELNONSIG               32917
#define ID_BUTTON32918                  32918
#define ID_BUTTON32919                  32919
#define ID_BUTTON32920                  32920
#define ID_BUTTON32921                  32921
#define ID_SAVESETTINGS                 32922
#define ID_VIEW_RETRIEVE                32923
#define ID_VIEW_RECURSIVE               32924
#define ID_VIEW_FILTER_BAR              32925
#define ID_VIEW_MODIFIED                32927
#define ID_FILTERMASK                   32928
#define ID_VIEW_CONFLICT                32929
#define ID_VIEW_UNKNOWN                 32931
#define ID_VIEW_MISSING                 32932
#define ID_VIEW_ADDED                   32935
#define ID_VIEW_REMOVED                 32936
#define ID_VIEW_CHANGED                 32937
#define ID_VIEW_HIDEUNKNOWN             32938
#define ID_VIEW_CLEARALL                32939
#define ID_BUTTON32940                  32940
#define ID_QUERY_ANNOTATE               32941
#define ID_VIEW_BROWSELOCATION_REMOVEUNWANTED 32943
#define ID_USE_TCLSHELL                 32944
#define ID_USE_PYSHELL                  32945
#define ID_GRAPH_GRAPHOPTIONS           32946
#define ID_GRAPH_ADMINOPTIONS_CHANGELOGMESSAGE 32950
#define ID_GRAPH_ADMINOPTIONS_SETSTATE  32951
#define ID_GRAPH_ADMINOPTIONS_SETDESCRIPTION 32952
#define ID_VIEW_RESERVEDEDIT            32957
#define ID_VIEW_FORCEEDIT               32958
#define ID_VIEW_ADDU                    32960
#define ID_VIEW_HIDEMISSING             32975
#define ID_VIEW_FILTERBAR_ENABLE        32976
#define ID_VIEW_FILTERBAR_CLEARALL      32977
#define ID_VIEW_FILTERBAR_OPTIONS       32978
#define ID_VIEW_RETRIEVEAS              32982
#define ID_VIEW_OPENSEL                 32983
#define ID_VIEW_OPENSELAS               32984
#define ID_QUERY_SHELLACTION_DEFAULT    32986
#define ID_HELP_CVS                     32987
#define ID_QUERY_PROPERTIES             32988
#define ID_VIEW_NEWINSTANCE             32989
#define ID_SUBSTMODE_TEXT               32991
#define ID_SUBSTMODE_BINARY             32992
#define ID_SUBSTMODE_BINARYDELTA        32993
#define ID_SUBSTMODE_UNICODE            32994
#define ID_SUBSTMODE_EXTENDEDENCODING   32996
#define ID_SUBSTMODE_NOSUBSTITUTION     32997
#define ID_SUBSTMODE_SUBSTITUTEKEYWORD  32998
#define ID_SUBSTMODE_SUBSTITUTEVALUE    32999
#define ID_SUBSTMODE_LOCKERSNAME        33000
#define ID_SUBSTMODE_FORCERESERVEDEDIT  33001
#define ID_SUBSTMODE_UNIXLINEENDINGS    33002
#define ID_SUBSTMODE_COMPRESSDELTAS     33003
#define ID_WINDOW_CLOSEALL              33008
#define ID_QUERY_COMPARE                33009
#define ID_VIEW_EDITSELCONFLICT         33010
#define ID_VIEW_OPENSELANNOTATE         33011
#define ID_VIEW_EXPORT                  33012
#define ID_QUERY_COMMANDPROMPT          33016
#define ID_MACRO_START                  34000
#define ID_MACRO_SEL                    34100
#define ID_MACRO_ADMIN                  34200
#define ID_MACRO_END                    34200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         33017
#define _APS_NEXT_CONTROL_VALUE         1305
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
