/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_Alert (void);
GtkWidget* create_gcvs_Settings (void);
GtkWidget* create_UpdateDlg (void);
GtkWidget* create_PasswdDlg (void);
GtkWidget* create_AskYesNoDlg (void);
GtkWidget* create_CommitDlg (void);
GtkWidget* create_DiffDlg (void);
GtkWidget* create_CheckoutDlg (void);
GtkWidget* create_LogDlg (void);
GtkWidget* create_ImportFilterDlg (void);
GtkWidget* create_ImpWarningDlg (void);
GtkWidget* create_ImpEntryDlg (void);
GtkWidget* create_ImportDlg (void);
GtkWidget* create_CmdlineDlg (void);
GtkWidget* create_TagModDlg (void);
GtkWidget* create_UntagModDlg (void);
GtkWidget* create_BranchModDlg (void);
GtkWidget* create_TagDlg (void);
GtkWidget* create_UntagDlg (void);
GtkWidget* create_BranchDlg (void);
GtkWidget* create_GraphWindow (void);
GtkWidget* create_SettingsDlg (void);
GtkWidget* create_AboutDlg (void);
GtkWidget* create_SelTagBranchDlg (void);
GtkWidget* create_SelDetailsDlg (void);
